spring:
  redis:
      host: 45.40.249.189
      port: 6379
      password: 123456
      database: 1
      timeout: 100
      pool:
          max-active: 8
          min-idle: 0
          max-idle: 8
          max-wait: -1